# Advent of Code 2024 - Day 4

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# Load input data
input_file = os.path.join("/home/jits/adventOfCode/2024/day4", "day4.txt")
with open(input_file, "r") as file:
    data = file.read().strip()
test_input_file = os.path.join("/home/jits/adventOfCode/2024/day4", "day4test.txt")
with open(test_input_file, "r") as test_file:
    test_data = test_file.read().strip()

# Example usage
print(test_data)  # Print the test data

MMMSXXMASM
MSAMXMSMSA
AMXSXMAAMM
MSAMASMSMX
XMASAMXAMM
XXAMMXXAMA
SMSMSASXSS
SAXAMASAAA
MAMMMXMMMM
MXMXAXMASX


## Process Input

In [20]:
# Process the input data
def process_input(data):
    translation_dict = {'X': 0, 'M': 1, 'A': 2, 'S': 3}
    list_of_strings = data.split("\n")
    processed_data = np.array([[translation_dict[char] for char in line] for line in list_of_strings])
    return processed_data
processed_data = process_input(test_data)
print(processed_data)


[[1 1 1 3 0 0 1 2 3 1]
 [1 3 2 1 0 1 3 1 3 2]
 [2 1 0 3 0 1 2 2 1 1]
 [1 3 2 1 2 3 1 3 1 0]
 [0 1 2 3 2 1 0 2 1 1]
 [0 0 2 1 1 0 0 2 1 2]
 [3 1 3 1 3 2 3 0 3 3]
 [3 2 0 2 1 2 3 2 2 2]
 [1 2 1 1 1 0 1 1 1 1]
 [1 0 1 0 2 0 1 2 3 0]]


## Part 1

In [32]:
processed_data = process_input(data)
count = 0
# count the horizontals
for row in processed_data:
    # count the number of times the order 0, 1, 2, 3 occurs. ie. 0 0 1 2 3 0 0 3 3 0 2 1 2 3 0 1 2 3 contains 2 times 0, 1, 2, 3
    for i in range(len(row) - 3):
        if np.array_equal(row[i:i+4], [0, 1, 2, 3]):
            count += 1
        elif np.array_equal(row[i:i+4], [3, 2, 1, 0]):
            count += 1


print(count)

# count the verticals
for i in range(len(processed_data[0])):
    for j in range(len(processed_data) - 3):
        if np.array_equal(processed_data[j:j+4, i], [0, 1, 2, 3]):
            count += 1
        elif np.array_equal(processed_data[j:j+4, i], [3, 2, 1, 0]):
            count += 1

print(count)
    
# count the diagonals (top left to bottom right)
for i in range(len(processed_data) - 3):
    for j in range(len(processed_data[0]) - 3):
        if np.array_equal([processed_data[i, j], processed_data[i+1, j+1], processed_data[i+2, j+2], processed_data[i+3, j+3]], [0, 1, 2, 3]):
            count += 1
        elif np.array_equal([processed_data[i, j], processed_data[i+1, j+1], processed_data[i+2, j+2], processed_data[i+3, j+3]], [3, 2, 1, 0]):
            count += 1

print(count)

# count the diagonals (top right to bottom left)
for i in range(len(processed_data) - 3):
    for j in range(3, len(processed_data[0])):
        if np.array_equal([processed_data[i, j], processed_data[i+1, j-1], processed_data[i+2, j-2], processed_data[i+3, j-3]], [0, 1, 2, 3]):
            count += 1
        elif np.array_equal([processed_data[i, j], processed_data[i+1, j-1], processed_data[i+2, j-2], processed_data[i+3, j-3]], [3, 2, 1, 0]):
            count += 1

print(count)

407
831
1606
2427


## Part 2

In [37]:
processed_data = process_input(data)
count = 0

# iterate over all the rows and columns
for x in range(1, len(processed_data) - 1):
    for y in range(1, len(processed_data[0]) - 1):
        # check if this contains a 2
        if processed_data[x, y] == 2:
            # check if x-1, y-1 contains 1 AND x+1, y+1 contains 3
            if (processed_data[x-1, y-1] == 1 and processed_data[x+1, y+1]) == 3 or (processed_data[x-1, y-1] == 3 and processed_data[x+1, y+1] == 1):
                if (processed_data[x+1, y-1] == 1 and processed_data[x-1, y+1]) == 3 or (processed_data[x+1, y-1] == 3 and processed_data[x-1, y+1] == 1):
                    count += 1
print(count)

1900
